# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dyong.com
email: likedyong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of dyong. It's about programming, software engineering, 
  web development, programming languages like c/c++, java, javascript, and etc. 
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

gems: ["jekyll-paginate", "jekyll-utf8"]

paginate: 5

github_username: dyong0
github_url : https://github.com/dyong0

# Build settings
markdown: kramdown
